export const cardsTrain = {
  sound: {},

  'Animals (Set-1)': {
    first: {
      word: 'Cow',
      translation: 'Корова',
      image: '../assets/img/animals-set-1/cow.svg',
      audioSRC: '../assets/audio/animals-set-1/Cow.mp3',
    },
    second: {
      word: 'Fox',
      translation: 'Лиса',
      image: '../assets/img/animals-set-1/fox.svg',
      audioSRC: '../assets/audio/animals-set-1/Fox.mp3',
    },
    third: {
      word: 'Giraffe',
      translation: 'Жираф',
      image: '../assets/img/animals-set-1/giraffe.svg',
      audioSRC: '../assets/audio/animals-set-1/Giraffe.mp3',
    },
    fourth: {
      word: 'Hare',
      translation: 'Заяц',
      image: '../assets/img/animals-set-1/hare.svg',
      audioSRC: '../assets/audio/animals-set-1/Hare.mp3',
    },
    fifes: {
      word: 'Mouse',
      translation: 'Мышь',
      image: '../assets/img/animals-set-1/mouse.svg',
      audioSRC: '../assets/audio/animals-set-1/Mouse.mp3',
    },
    six: {
      word: 'Panda',
      translation: 'Панда',
      image: '../assets/img/animals-set-1/panda.svg',
      audioSRC: '../assets/audio/animals-set-1/Panda.mp3',
    },
    sevens: {
      word: 'Penguin',
      translation: 'Пингвин',
      image: '../assets/img/animals-set-1/penguin.svg',
      audioSRC: '../assets/audio/animals-set-1/Penguin.mp3',
    },
    eighth: {
      word: 'Sparrow',
      translation: 'Воробей',
      image: '../assets/img/animals-set-1/sparrow.svg',
      audioSRC: '../assets/audio/animals-set-1/Sparrow.mp3',
    },
  },

  'Animals (Set-2)': {
    first: {
      word: 'Bear',
      translation: 'Медведь',
      image: '../assets/img/animals-set-2/bear.svg',
      audioSRC: '../assets/audio/animals-set-2/Bear.mp3',
    },
    second: {
      word: 'Bull',
      translation: 'Бык',
      image: '../assets/img/animals-set-2/bull.svg',
      audioSRC: '../assets/audio/animals-set-2/Bull.mp3',
    },
    third: {
      word: 'Camel',
      translation: 'Верблюд',
      image: '../assets/img/animals-set-2/camel.svg',
      audioSRC: '../assets/audio/animals-set-2/Camel.mp3',
    },
    fourth: {
      word: 'Crab',
      translation: 'Краб',
      image: '../assets/img/animals-set-2/crab.svg',
      audioSRC: '../assets/audio/animals-set-2/Crab.mp3',
    },
    fifes: {
      word: 'Peacock',
      translation: 'Павлин',
      image: '../assets/img/animals-set-2/peacock.svg',
      audioSRC: '../assets/audio/animals-set-2/Peacock.mp3',
    },
    six: {
      word: 'Pig',
      translation: 'Свинья',
      image: '../assets/img/animals-set-2/pig.svg',
      audioSRC: '../assets/audio/animals-set-2/Pig.mp3',
    },
    sevens: {
      word: 'Sheep',
      translation: 'Овца',
      image: '../assets/img/animals-set-2/sheep.svg',
      audioSRC: '../assets/audio/animals-set-2/Sheep.mp3',
    },
    eighth: {
      word: 'Turtle',
      translation: 'Черепаха',
      image: '../assets/img/animals-set-2/turtle.svg',
      audioSRC: '../assets/audio/animals-set-2/Turtle.mp3',
    },
  },

  'Animals (Set-3)': {
    first: {
      word: 'Battleship',
      translation: 'Броненосец',
      image: '../assets/img/animals-set-3/battleship.svg',
      audioSRC: '../assets/audio/animals-set-3/Battleship.mp3',
    },
    second: {
      word: 'Cat',
      translation: 'Кот',
      image: '../assets/img/animals-set-3/cat.svg',
      audioSRC: '../assets/audio/animals-set-3/Cat.mp3',
    },
    third: {
      word: 'Dog',
      translation: 'Собака',
      image: '../assets/img/animals-set-3/dog.svg',
      audioSRC: '../assets/audio/animals-set-3/Dog.mp3',
    },
    fourth: {
      word: 'Elephant',
      translation: 'Слон',
      image: '../assets/img/animals-set-3/elephant.svg',
      audioSRC: '../assets/audio/animals-set-3/Elephant.mp3',
    },
    fifes: {
      word: 'Gull',
      translation: 'Чайка',
      image: '../assets/img/animals-set-3/gull.svg',
      audioSRC: '../assets/audio/animals-set-3/Gull.mp3',
    },
    six: {
      word: 'Raccoon',
      translation: 'Енот',
      image: '../assets/img/animals-set-3/raccoon.svg',
      audioSRC: '../assets/audio/animals-set-3/Raccoon.mp3',
    },
    sevens: {
      word: 'Sloth',
      translation: 'Ленивец',
      image: '../assets/img/animals-set-3/sloth.svg',
      audioSRC: '../assets/audio/animals-set-3/Sloth.mp3',
    },
    eighth: {
      word: 'Tiger',
      translation: 'Тигр',
      image: '../assets/img/animals-set-3/tiger.svg',
      audioSRC: '../assets/audio/animals-set-3/Tiger.mp3',
    },
  },

  Food: {
    first: {
      word: 'Bread',
      translation: 'Хлеб',
      image: '../assets/img/food/bread.svg',
      audioSRC: '../assets/audio/food/Bread.mp3',
    },
    second: {
      word: 'Cake',
      translation: 'Торт',
      image: '../assets/img/food/dessert.svg',
      audioSRC: '../assets/audio/food/Cake.mp3',
    },
    third: {
      word: 'Fish',
      translation: 'Рыба',
      image: '../assets/img/food/fish.svg',
      audioSRC: '../assets/audio/food/Fish.mp3',
    },
    fourth: {
      word: 'French fries',
      translation: 'Картофель фри',
      image: '../assets/img/food/french-fries.svg',
      audioSRC: '../assets/audio/food/French-fries.mp3',
    },
    fifes: {
      word: 'Omelet',
      translation: 'Омлет',
      image: '../assets/img/food/frying-pan.svg',
      audioSRC: '../assets/audio/food/Omelet.mp3',
    },
    six: {
      word: 'Honey',
      translation: 'Mед',
      image: '../assets/img/food/honey.svg',
      audioSRC: '../assets/audio/food/Honey.mp3',
    },
    sevens: {
      word: 'Pizza',
      translation: 'Пицца',
      image: '../assets/img/food/pizza.svg',
      audioSRC: '../assets/audio/food/Pizza.mp3',
    },
    eighth: {
      word: 'Pumpkin',
      translation: 'Тыква',
      image: '../assets/img/food/pumpkin.svg',
      audioSRC: '../assets/audio/food/Pumpkin.mp3',
    },
  },
  'Fruits and berries': {
    first: {
      word: 'Apple',
      translation: 'Яблоко',
      image: '../assets/img/fruits-and-berries/apple.svg',
      audioSRC: '../assets/audio/fruits-and-berries/Apple.mp3',
    },
    second: {
      word: 'Banana',
      translation: 'Банан',
      image: '../assets/img/fruits-and-berries/banana.svg',
      audioSRC: '../assets/audio/fruits-and-berries/Banana.mp3',
    },
    third: {
      word: 'Blueberry',
      translation: 'Черника',
      image: '../assets/img/fruits-and-berries/blueberry.svg',
      audioSRC: '../assets/audio/fruits-and-berries/Blueberry.mp3',
    },
    fourth: {
      word: 'Cherries',
      translation: 'Вишня',
      image: '../assets/img/fruits-and-berries/cherries.svg',
      audioSRC: '../assets/audio/fruits-and-berries/Cherries.mp3',
    },
    fifes: {
      word: 'Grapes',
      translation: 'Виноград',
      image: '../assets/img/fruits-and-berries/grapes.svg',
      audioSRC: '../assets/audio/fruits-and-berries/Grapes.mp3',
    },
    six: {
      word: 'Lemon',
      translation: 'Лимон',
      image: '../assets/img/fruits-and-berries/lemon.svg',
      audioSRC: '../assets/audio/fruits-and-berries/Lemon.mp3',
    },
    sevens: {
      word: 'Pear',
      translation: 'Груша',
      image: '../assets/img/fruits-and-berries/pear.svg',
      audioSRC: '../assets/audio/fruits-and-berries/Pear.mp3',
    },
    eighth: {
      word: 'Pineapple',
      translation: 'Ананас',
      image: '../assets/img/fruits-and-berries/pineapple.svg',
      audioSRC: '../assets/audio/fruits-and-berries/Pineapple.mp3',
    },
  },

  Professions: {
    first: {
      word: 'Athlete',
      translation: 'Спортсмен',
      image: '../assets/img/professions/athlete.svg',
      audioSRC: '../assets/audio/professions/Athlete.mp3',
    },
    second: {
      word: 'Cook',
      translation: 'Повар',
      image: '../assets/img/professions/chef.svg',
      audioSRC: '../assets/audio/professions/Cook.mp3',
    },
    third: {
      word: 'Cosmonaut',
      translation: 'Космонавт',
      image: '../assets/img/professions/cosmonaut.svg',
      audioSRC: '../assets/audio/professions/Cosmonaut.mp3',
    },
    fourth: {
      word: 'Doctor',
      translation: 'Доктор',
      image: '../assets/img/professions/doctor.svg',
      audioSRC: '../assets/audio/professions/Doctor.mp3',
    },
    fifes: {
      word: 'Farmer',
      translation: 'Фермер',
      image: '../assets/img/professions/farmer.svg',
      audioSRC: '../assets/audio/professions/Farmer.mp3',
    },
    six: {
      word: 'Programmer',
      translation: 'Программист',
      image: '../assets/img/professions/programmer.svg',
      audioSRC: '../assets/audio/professions/Programmer.mp3',
    },
    sevens: {
      word: 'Teacher',
      translation: 'Учитель',
      image: '../assets/img/professions/teacher.svg',
      audioSRC: '../assets/audio/professions/Teacher.mp3',
    },
    eighth: {
      word: 'Builder',
      translation: 'Строитель',
      image: '../assets/img/professions/worker.svg',
      audioSRC: '../assets/audio/professions/Builder.mp3',
    },
  },

  Clothes: {
    first: {
      word: 'Cap',
      translation: 'Кепка',
      image: '../assets/img/clothes/baseball-cap.svg',
      audioSRC: '../assets/audio/clothes/Cap.mp3',
    },
    second: {
      word: 'Dress',
      translation: 'Платье',
      image: '../assets/img/clothes/dress.svg',
      audioSRC: '../assets/audio/clothes/Dress.mp3',
    },
    third: {
      word: 'T-shirt',
      translation: 'Футболка',
      image: '../assets/img/clothes/shirt.svg',
      audioSRC: '../assets/audio/clothes/T-shirt.mp3',
    },
    fourth: {
      word: 'Shorts',
      translation: 'Шорты',
      image: '../assets/img/clothes/shorts.svg',
      audioSRC: '../assets/audio/clothes/Shorts.mp3',
    },
    fifes: {
      word: 'Skirt',
      translation: 'Юбка',
      image: '../assets/img/clothes/skirt.svg',
      audioSRC: '../assets/audio/clothes/Skirt.mp3',
    },
    six: {
      word: 'Glasses',
      translation: 'Очки',
      image: '../assets/img/clothes/sunglasses.svg',
      audioSRC: '../assets/audio/clothes/Glasses.mp3',
    },
    sevens: {
      word: 'Sneakers',
      translation: 'Кросовки',
      image: '../assets/img/clothes/trainer.svg',
      audioSRC: '../assets/audio/clothes/Sneakers.mp3',
    },
    eighth: {
      word: 'Trousers',
      translation: 'Штаны',
      image: '../assets/img/clothes/trousers.svg',
      audioSRC: '../assets/audio/clothes/Trousers.mp3',
    },
  },
  Places: {
    first: {
      word: 'Desert',
      translation: 'Пустыня',
      image: '../assets/img/places/desert.svg',
      audioSRC: '../assets/audio/places/Desert.mp3',
    },
    second: {
      word: 'Forest',
      translation: 'Лес',
      image: '../assets/img/places/forest.svg',
      audioSRC: '../assets/audio/places/Forest.mp3',
    },
    third: {
      word: 'Beach',
      translation: 'Пляж',
      image: '../assets/img/places/island.svg',
      audioSRC: '../assets/audio/places/Beach.mp3',
    },
    fourth: {
      word: 'Mountains',
      translation: 'Горы',
      image: '../assets/img/places/mountain.svg',
      audioSRC: '../assets/audio/places/Mountains.mp3',
    },
    fifes: {
      word: 'River',
      translation: 'Река',
      image: '../assets/img/places/river.svg',
      audioSRC: '../assets/audio/places/River.mp3',
    },
    six: {
      word: 'Road',
      translation: 'Дорога',
      image: '../assets/img/places/road.svg',
      audioSRC: '../assets/audio/places/Road.mp3',
    },
    sevens: {
      word: 'City',
      translation: 'Город',
      image: '../assets/img/places/town.svg',
      audioSRC: '../assets/audio/places/City.mp3',
    },
    eighth: {
      word: 'Village',
      translation: 'Деревня',
      image: '../assets/img/places/windmill.svg',
      audioSRC: '../assets/audio/places/Village.mp3',
    },
  },
};
